# ----------------------- #
#      Main Configs       #
# ----------------------- #
baseurl: ''
domain: 'http://bridalsuite.blackbride.com'

title: Black Bride Vendors
email: info@blackbride.com
author: Jessica Skeete
description: 'Our Purpose is to serve women of color in planning their dream wedding by providing exceptional wedding inspiration and access to fine vendors around the world. This site is to help vendors in the community do the same.'
copyright: 'Copyright &copy; 2016  Black Bride Magazine. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/blackbrideUSA/
  - title: instagram
    url: https://www.instagram.com/blackbride1998/?hl=en
  - title: twitter
    url: https://twitter.com/blackbride?lang=en
